export const escenariosPrueba = [
  {
    nombre: "Escenario 1: Persona sin riesgo",
    data: {
      persona: {
        nombre: "Ana",
        apellido: "Torres",
        documento_tipo: "RUT",
        documento_numero: "22.222.222-2",
        nacionalidad: "Chilena",
        fecha_nacimiento: "1995-04-12",
        telefono: "+56 9 2222 2222",
        email: "ana.torres@mail.com"
      },
      vehiculo: {
        tipo: "Particular",
        patente: "AA1122",
        pais_origen: "Chile",
        marca: "Toyota",
        modelo: "Yaris",
        anio: "2020",
        color: "Blanco",
        chasis: "CHASIS-AA1122",
        motor: "MOTOR-AA1122"
      },
      declaracion: {
        transporta_alimentos: false,
        transporta_vegetales: false,
        transporta_animales: false,
        dinero_mayor_declarable: false,
        observaciones: ""
      },
      motivo_viaje: "Turismo",
      destino: "Argentina",
      frontera: "Complejo Los Libertadores"
    }
  },
  {
    nombre: "Escenario 2: Persona con antecedente",
    data: {
      persona: {
        nombre: "Carlos",
        apellido: "Soto",
        documento_tipo: "RUT",
        documento_numero: "12.345.678-5",
        nacionalidad: "Chilena",
        fecha_nacimiento: "1988-09-20",
        telefono: "+56 9 1234 5678",
        email: "carlos.soto@mail.com"
      },
      vehiculo: {
        tipo: "Particular",
        patente: "BB2233",
        pais_origen: "Chile",
        marca: "Hyundai",
        modelo: "Accent",
        anio: "2018",
        color: "Gris",
        chasis: "CHASIS-BB2233",
        motor: "MOTOR-BB2233"
      },
      declaracion: {
        transporta_alimentos: false,
        transporta_vegetales: false,
        transporta_animales: false,
        dinero_mayor_declarable: false,
        observaciones: "Viaje particular."
      },
      motivo_viaje: "Turismo",
      destino: "Mendoza",
      frontera: "Complejo Los Libertadores"
    }
  },
  {
    nombre: "Escenario 3: Declaración SAG",
    data: {
      persona: {
        nombre: "María",
        apellido: "González",
        documento_tipo: "RUT",
        documento_numero: "33.333.333-3",
        nacionalidad: "Chilena",
        fecha_nacimiento: "1990-01-18",
        telefono: "+56 9 3333 3333",
        email: "maria.gonzalez@mail.com"
      },
      vehiculo: {
        tipo: "Particular",
        patente: "CC3344",
        pais_origen: "Chile",
        marca: "Kia",
        modelo: "Rio",
        anio: "2021",
        color: "Azul",
        chasis: "CHASIS-CC3344",
        motor: "MOTOR-CC3344"
      },
      declaracion: {
        transporta_alimentos: true,
        transporta_vegetales: true,
        transporta_animales: false,
        dinero_mayor_declarable: false,
        observaciones: "Transporta frutas y alimentos envasados."
      },
      motivo_viaje: "Turismo",
      destino: "Argentina",
      frontera: "Complejo Los Libertadores"
    }
  },
  {
    nombre: "Escenario 4: Alto riesgo",
    data: {
      persona: {
        nombre: "Pedro",
        apellido: "Morales",
        documento_tipo: "RUT",
        documento_numero: "11.111.111-1",
        nacionalidad: "Chilena",
        fecha_nacimiento: "1982-06-03",
        telefono: "+56 9 1111 1111",
        email: "pedro.morales@mail.com"
      },
      vehiculo: {
        tipo: "Carga",
        patente: "ZZ9999",
        pais_origen: "Chile",
        marca: "Volvo",
        modelo: "FH",
        anio: "2017",
        color: "Rojo",
        chasis: "CHASIS-ZZ9999",
        motor: "MOTOR-ZZ9999"
      },
      declaracion: {
        transporta_alimentos: true,
        transporta_vegetales: true,
        transporta_animales: true,
        dinero_mayor_declarable: true,
        observaciones: "Carga declarada con productos sensibles."
      },
      motivo_viaje: "Comercio",
      destino: "Argentina",
      frontera: "Complejo Los Libertadores"
    }
  },
  {
    nombre: "Viaje familiar con 1 menor",
    data: {
      persona: {
        nombre: "Ana",
        apellido: "Torres",
        documento_tipo: "RUT",
        documento_numero: "22.222.222-2",
        nacionalidad: "Chilena",
        fecha_nacimiento: "1995-04-12",
        telefono: "+56 9 2222 2222",
        email: "ana.torres@mail.com",
      },
      vehiculo: {
        tipo: "Particular",
        patente: "FT1234",
        pais_origen: "Chile",
        marca: "Hyundai",
        modelo: "Tucson",
        anio: "2021",
        color: "Gris",
        chasis: "",
        motor: "",
      },
      declaracion: {
        transporta_alimentos: false,
        transporta_vegetales: false,
        transporta_animales: false,
        dinero_mayor_declarable: false,
        observaciones: "",
      },
      motivo_viaje: "Turismo",
      destino: "Argentina",
      frontera: "Complejo Los Libertadores",
      menores: [
        {
          nombre: "Sofía",
          apellido: "Torres",
          documento_tipo: "RUT",
          documento_numero: "23.456.789-6",
          nacionalidad: "Chilena",
          fecha_nacimiento: "2015-04-12",
          parentesco: "Hijo/a",
          autorizacion_viaje: "Viaja con ambos padres",
          observaciones: "Menor viaja acompañada por adulto responsable.",
        },
      ],
    },
  },
  {
    nombre: "Viaje familiar con 2 menores",
    data: {
      persona: {
        nombre: "Marcelo",
        apellido: "Rojas",
        documento_tipo: "RUT",
        documento_numero: "20.123.456-5",
        nacionalidad: "Chilena",
        fecha_nacimiento: "1988-08-20",
        telefono: "+56 9 3333 3333",
        email: "marcelo.rojas@mail.com",
      },
      vehiculo: {
        tipo: "Particular",
        patente: "MR2026",
        pais_origen: "Chile",
        marca: "Toyota",
        modelo: "Corolla",
        anio: "2022",
        color: "Blanco",
        chasis: "",
        motor: "",
      },
      declaracion: {
        transporta_alimentos: false,
        transporta_vegetales: false,
        transporta_animales: false,
        dinero_mayor_declarable: false,
        observaciones: "",
      },
      motivo_viaje: "Turismo",
      destino: "Argentina",
      frontera: "Complejo Los Libertadores",
      menores: [
        {
          nombre: "Mateo",
          apellido: "Rojas",
          documento_tipo: "RUT",
          documento_numero: "21.456.789-K",
          nacionalidad: "Chilena",
          fecha_nacimiento: "2014-11-05",
          parentesco: "Hijo/a",
          autorizacion_viaje: "Viaja con ambos padres",
          observaciones: "",
        },
        {
          nombre: "Valentina",
          apellido: "Rojas",
          documento_tipo: "RUT",
          documento_numero: "24.567.890-8",
          nacionalidad: "Chilena",
          fecha_nacimiento: "2018-02-15",
          parentesco: "Hijo/a",
          autorizacion_viaje: "Viaja con ambos padres",
          observaciones: "",
        },
      ],
    },
  },
  {
    nombre: "Menor con autorización pendiente",
    data: {
      persona: {
        nombre: "Carolina",
        apellido: "Muñoz",
        documento_tipo: "RUT",
        documento_numero: "19.456.789-8",
        nacionalidad: "Chilena",
        fecha_nacimiento: "1990-06-18",
        telefono: "+56 9 4444 4444",
        email: "carolina.munoz@mail.com",
      },
      vehiculo: {
        tipo: "Particular",
        patente: "CM4455",
        pais_origen: "Chile",
        marca: "Kia",
        modelo: "Rio",
        anio: "2020",
        color: "Rojo",
        chasis: "",
        motor: "",
      },
      declaracion: {
        transporta_alimentos: false,
        transporta_vegetales: false,
        transporta_animales: false,
        dinero_mayor_declarable: false,
        observaciones: "Viaje con menor cuya documentación será revisada por Aduanas.",
      },
      motivo_viaje: "Turismo",
      destino: "Argentina",
      frontera: "Complejo Los Libertadores",
      menores: [
        {
          nombre: "Emilia",
          apellido: "Muñoz",
          documento_tipo: "RUT",
          documento_numero: "20.765.432-9",
          nacionalidad: "Chilena",
          fecha_nacimiento: "2017-09-22",
          parentesco: "Hijo/a",
          autorizacion_viaje: "Documento pendiente de revisión",
          observaciones: "Debe presentar autorización notarial al momento del control.",
        },
      ],
    },
  },
  {
    nombre: "Tutor legal con menor extranjero",
    data: {
      persona: {
        nombre: "Javier",
        apellido: "Pérez",
        documento_tipo: "RUT",
        documento_numero: "18.456.789-K",
        nacionalidad: "Chilena",
        fecha_nacimiento: "1985-03-10",
        telefono: "+56 9 5555 5555",
        email: "javier.perez@mail.com",
      },
      vehiculo: {
        tipo: "Particular",
        patente: "JP7788",
        pais_origen: "Chile",
        marca: "Nissan",
        modelo: "Versa",
        anio: "2019",
        color: "Azul",
        chasis: "",
        motor: "",
      },
      declaracion: {
        transporta_alimentos: false,
        transporta_vegetales: false,
        transporta_animales: false,
        dinero_mayor_declarable: false,
        observaciones: "",
      },
      motivo_viaje: "Turismo",
      destino: "Argentina",
      frontera: "Complejo Los Libertadores",
      menores: [
        {
          nombre: "Lucas",
          apellido: "Fernández",
          documento_tipo: "Pasaporte",
          documento_numero: "PA123456",
          nacionalidad: "Argentina",
          fecha_nacimiento: "2016-07-30",
          parentesco: "Tutor legal",
          autorizacion_viaje: "Presenta autorización de viaje",
          observaciones: "Menor extranjero viaja con tutor legal.",
        },
      ],
    },
  },
  {
    nombre: "Viaje con menor y alimentos declarados",
    data: {
      persona: {
        nombre: "Paula",
        apellido: "Herrera",
        documento_tipo: "RUT",
        documento_numero: "25.432.109-5",
        nacionalidad: "Chilena",
        fecha_nacimiento: "1993-12-02",
        telefono: "+56 9 6666 6666",
        email: "paula.herrera@mail.com",
      },
      vehiculo: {
        tipo: "Particular",
        patente: "PH9090",
        pais_origen: "Chile",
        marca: "Chevrolet",
        modelo: "Onix",
        anio: "2021",
        color: "Negro",
        chasis: "",
        motor: "",
      },
      declaracion: {
        transporta_alimentos: true,
        transporta_vegetales: false,
        transporta_animales: false,
        dinero_mayor_declarable: false,
        observaciones: "Transporta alimentos envasados para consumo familiar.",
      },
      motivo_viaje: "Turismo",
      destino: "Argentina",
      frontera: "Complejo Los Libertadores",
      menores: [
        {
          nombre: "Isidora",
          apellido: "Herrera",
          documento_tipo: "RUT",
          documento_numero: "26.789.456-6",
          nacionalidad: "Chilena",
          fecha_nacimiento: "2020-01-14",
          parentesco: "Hijo/a",
          autorizacion_viaje: "Viaja con ambos padres",
          observaciones: "",
        },
      ],
    },
  },
];